package service.excel;

public interface IExcelTableColumns {

    String TAXON_COLUMN_ID = "TAXON_COLUMN_ID";// 0;
    String ORIGINAL_NAME_COLUMN_ID = "ORIGINAL_NAME_COLUMN_ID";//1;
    String LOCALITY_COLUMN_ID = "LOCALITY_COLUMN_ID";//2;
    String NEAREST_TOWN_COLUMN_ID = "NEAREST_TOWN_COLUMN_ID";//3;
    String DISTRICT_COLUMN_ID = "DISTRICT_COLUMN_ID";//4;
    String ALTITUDE_COLUMN_ID = "ALTITUDE_COLUMN_ID";//5;
    String GPS_COORDS_COLUMN_ID = "GPS_COORDS_COLUMN_ID";//6;
    String GPS_COORDS_SOURCE_COLUMN_ID = "GPS_COORDS_SOURCE_COLUMN_ID";//7;
    String GPS_COORDS_PRECISION_COLUMN_ID = "GPS_COORDS_PRECISION_COLUMN_ID";//8;

    String DATE_COLUMN_ID = "DATE_COLUMN_ID";//9;
    String FINDER_COLUMN_ID = "FINDER_COLUMN_ID";//10;
    String SOURCE_COLUMN_ID = "SOURCE_COLUMN_ID";//11;
    String PHYTOCHORION_COLUMN_ID = "PHYTOCHORION_COLUMN_ID";//12;
    String SQUARE_COLUMN_ID = "SQUARE_COLUMN_ID";//13;
    String COMMENT_COLUMN_ID = "COMMENT_COLUMN_ID";//14;

    String FOREIGN_COLUMN_ID = "FOREIGN_COLUMN_ID";//15;
    String LICENSE_COLUMN_ID = "LICENSE_COLUMN_ID";//16;
    String GPS_URL_COLUMN_ID = "GPS_URL_COLUMN_ID";//17;

    String ERROR_REPORT_COLUMN_ID = "ERROR_REPORT_COLUMN_ID";//18;  //16 (inlcude GPS_URL on col 15)
    String INFO_REPORT_COLUMN_ID = "INFO_REPORT_COLUMN_ID";//19;   //17
    String WARNING_REPORT_COLUMN_ID = "WARNING_REPORT_COLUMN_ID";//20; //18

    String DETREV_ID = "DETREV_ID";

    String REMARK_EXCERPTION_ID = "REMARK_EXCERPTION_ID";
    String REMARK_OTHER_ID = "REMARK_OTHER_ID";
    String REMARK_DOUBT_ID = "REMARK_DOUBT_ID";

    String ENVIRONMENT_ID = "ENVIRONMENT_ID";

    //non-vascular only:
    String SUBSTRATE_NOTE_COLUMN_ID = "SUBSTRATE_NOTE_COLUMN_ID";
    String CHEMICAL_DATA_COLUMN_ID = "CHEMICAL_DATA_COLUMN_ID";
    String HERBARIUM_COLUMN_ID = "HERBARIUM_COLUMN_ID";

    String LOCALITY_AUXILIARY_COLUMN_ID = "LOCALITY_AUXILIARY_COLUMN_ID";
    String SUBSTRATE1_COLUMN_ID = "SUBSTRATE1_COLUMN_ID";
    String SUBSTRATE2_COLUMN_ID = "SUBSTRATE2_COLUMN_ID";

}
