package controllers.atlas;

import controllers.ControllerBase;
import controllers.security.Authorized;
import dto.atlas.RecordHistoryDto;
import io.ebean.ExpressionList;
import models.RecordHistory;
import models.User;
import play.i18n.Messages;
import play.libs.Json;
import play.mvc.Http;
import play.mvc.Result;
import play.mvc.Security;
import utils.JsonResult;
import utils.SessionUtils;

import java.util.List;

/**
 * Controller for record history endpoint.
 * Provides pagination, filtering, and sorting support for record change history.
 */
@Security.Authenticated(Authorized.class)
public class RecordHistoryController extends ControllerBase {

    /**
     * GET /atlas/record/history/:recordId
     * Get paginated history for a specific record with optional filtering and sorting.
     * <p>
     * Query params (auto-generated by DataTable):
     * - page: Page number (default: 1)
     * - pageSize: Items per page (default: 20)
     * - sortBy: Field to sort by (id, changeType, fieldDesc, createTimestamp)
     * - sortOrder: Sort direction (asc or desc, default: desc)
     * - UserNameFilter: Optional filter for user name
     * - FieldDescFilter: Optional filter for field description
     * - ChangeTypeFilter: Optional filter by change type (LOCATION, DESCRIPTION, FLAG, COMMENT, TAXON)
     * - OldValueFilter: Optional filter for old value
     * - NewValueFilter: Optional filter for new value
     */
    public Result getRecordHistory(Http.Request request, Long recordId) {
        Messages messages = getMessages(request);
        User currentUser = SessionUtils.getCurrentUser(request.session());

        if (currentUser == null) {
            return unauthorized(JsonResult.error(messages.at("error.unauthorized")));
        }

        // Get query parameters
        String pageParam = request.queryString("page").orElse("1");
        String pageSizeParam = request.queryString("pageSize").orElse("20");
        String sortBy = request.queryString("sortBy").orElse("createTimestamp");
        String sortOrder = request.queryString("sortOrder").orElse("desc");

        // Get filters (DataTable uses camelCase with "Filter" suffix)
        String userNameFilter = request.queryString("UserNameFilter").orElse(null);
        String fieldDescFilter = request.queryString("FieldDescFilter").orElse(null);
        String changeTypeFilter = request.queryString("ChangeTypeFilter").orElse(null);
        String oldValueFilter = request.queryString("OldValueFilter").orElse(null);
        String newValueFilter = request.queryString("NewValueFilter").orElse(null);

        int page;
        int pageSize;

        try {
            page = Integer.parseInt(pageParam);
            pageSize = Integer.parseInt(pageSizeParam);
            if (page < 1) page = 1;
            if (pageSize < 1) pageSize = 20;
            if (pageSize > 100) pageSize = 100; // Max page size
        } catch (NumberFormatException e) {
            page = 1;
            pageSize = 20;
        }

        // Validate sort field
        List<String> validSortFields = List.of("id", "changeType", "fieldDesc", "createTimestamp", "userName", "oldValue", "newValue");
        if (!validSortFields.contains(sortBy)) {
            sortBy = "createTimestamp";
        }

        // Validate sort order
        if (!"asc".equalsIgnoreCase(sortOrder) && !"desc".equalsIgnoreCase(sortOrder)) {
            sortOrder = "desc";
        }

        try {
            // Build query
            ExpressionList<RecordHistory> query = RecordHistory.find().query()
                .where()
                .eq("recordId", recordId);

            // Apply filters
            if (fieldDescFilter != null && !fieldDescFilter.trim().isEmpty()) {
                String filterPattern = "%" + fieldDescFilter.toLowerCase() + "%";
                query.ilike("fieldDesc", filterPattern);
            }

            if (oldValueFilter != null && !oldValueFilter.trim().isEmpty()) {
                String filterPattern = "%" + oldValueFilter.toLowerCase() + "%";
                query.ilike("oldValue", filterPattern);
            }

            if (newValueFilter != null && !newValueFilter.trim().isEmpty()) {
                String filterPattern = "%" + newValueFilter.toLowerCase() + "%";
                query.ilike("newValue", filterPattern);
            }

            if (changeTypeFilter != null && !changeTypeFilter.trim().isEmpty()) {
                query.eq("changeType", changeTypeFilter.toUpperCase());
            }

            // Get total count before sorting
            int totalCount = query.findCount();

            // Apply sorting
            String order = sortOrder.equalsIgnoreCase("asc") ? "asc" : "desc";
            query.orderBy(String.format("%s %s", sortBy, order));

            // Apply pagination
            int offset = (page - 1) * pageSize;
            List<RecordHistory> histories = query.setFirstRow(offset).setMaxRows(pageSize).findList();

            // Convert to DTOs
            List<RecordHistoryDto> dtos = histories.stream()
                .map(RecordHistoryDto::fromRecordHistory)
                .toList();

            // Build response matching ServerSideDataResponse format expected by DataTable
            var response = Json.newObject();
            response.put("success", true);
            response.set("data", Json.toJson(dtos));
            response.put("totalCount", totalCount);
            response.put("filteredCount", totalCount); // We don't have separate filtered count

            return ok(response);

        } catch (Exception e) {
            return ok(JsonResult.error(e.getMessage()));
        }
    }

    /**
     * Paginated response wrapper for record history
     */
    public static class RecordHistoryPageResponse {
        public final List<RecordHistoryDto> data;
        public final int totalCount;
        public final int page;
        public final int pageSize;

        public RecordHistoryPageResponse(List<RecordHistoryDto> data, int totalCount, int page, int pageSize) {
            this.data = data;
            this.totalCount = totalCount;
            this.page = page;
            this.pageSize = pageSize;
        }
    }
}
