include "common"

user {
  MasterAdmin = 2                 # Reznickova
  TaxonManager = [1,4,5]               # Axmanova,Danihelka,Novotny
  TaxonRanksManager = 4         # Danihelka
  TraitMasterAdmin = 2          # Reznickova
  TraitUserAdmin = 2            # Reznickova
  
  AsyncImporters = []
}

license.default = "CC-BY-SA"  #default record license name
license.creative-commons-ids = ["CC-BY-SA", "CC-BY"]

taxonGroup = vascular #vascular|nonvascular

hasAtlasModule = false
hasTraitModule = true
hasBiblioModule = false
