include "common"

user {
  MasterAdmin = 10002                 # Man
  MapDesigners = [10002]        #
  TaxonManager = [10000,10001]               # Kucera,Malicek
  TaxonRanksManager = 10002         # Man
  HerbariumsManager = 10002
  FindersManager = 10002
  TraitMasterAdmin = 10002          #
  TraitUserAdmin = 10002            #
  MapUserAdmin = [10001,10002]                #
  BulkImporter = 10002          # hromadne importyXXX
  Florabase = 10002
  
  AsyncImporters = []
}

license.default = "CC-BY-SA"  #default record license name
license.creative-commons-ids = ["CC-BY-SA", "CC-BY"]

accessToken = AR1734ETRXYZW1047ZREQWAS

taxonGroup = nonvascular #vascular|nonvascular

hasAtlasModule = true
hasTraitModule = true
hasBiblioModule = false
