include "slovak"

db.default.url="jdbc:postgresql://pladias_master:5432/pladias_sk" 
db.default.username=play
db.default.password=play

#features to simplify debugging when developing new feature (this should never be set to true in production)
debug=true

# Geoserver configuration
geoserver.host=geoserverprivatesk
geoserver.port=8080

# Root logger:
logger.root=ERROR

# Logger used by the framework:
logger.play=INFO

# Logger provided to your application:
logger.application=DEBUG

license.default = "P-P-P"  #default record license name

play.filters.hosts {
  # Allow requests to example.com, its subdomains, and localhost.
  allowed = ["dalibor.ibot.cas.cz", "pladias.ibot.cas.cz", "pladias.cz", "localhost:9000", "localhost:9643"]
}
