include "dalibor"

db.default.url="jdbc:postgresql://pladias_master:5432/dalibor" 
db.default.username=play
db.default.password=play
#db.default.url="jdbc:postgresql://localhost:6543/dalibor" 
#db.default.username=pladias
#db.default.password=pladias


#features to simplify debugging when developing new feature (this should never be set to true in production)
debug=true

# Geoserver configuration
geoserver.host=geoserver_private_nonvascular
geoserver.port=8080

# Root logger:
logger.root=ERROR

# Logger used by the framework:
logger.play=INFO

# Logger provided to your application:
logger.application=DEBUG

license.default = "CC-BY-SA"  #default record license name

play.filters.hosts {
  # Allow requests to example.com, its subdomains, and localhost.
  allowed = ["dalibor.ibot.cas.cz", "pladias.ibot.cas.cz", "pladias.cz", "localhost:9000", "localhost:9543"]
}