include "cevs"

db.default.url="jdbc:postgresql://pladias_master:5432/cevs"
db.default.username=play
db.default.password=play

#features to simplify debugging when developing new feature (this should never be set to true in production)
debug=true

# Geoserver configuration
geoserver.host=geoserverprivatecevs
geoserver.port=8080

# Root logger:
logger.root=ERROR

# Logger used by the framework:
logger.play=INFO

# Logger provided to your application:
logger.application=DEBUG

license.default = "CC-BY-SA"  #default record license name

play.filters.hosts {
  # Allow requests to example.com, its subdomains, and localhost.
  allowed = ["cevs.ibot.cas.cz",  "localhost:9000", "localhost:9643"]
}