# Ebean Migration Configuration
# This file can be overridden by a file with the same name on the classpath

# Migrations are stored here
migration.migrationPath=dbmigration
migration.migrationInitPath=dbmigration

# Database platform
migration.platform=postgres

# Migration tracking table
migration.table=db_migration
migration.metaTable=db_migration_meta

# Baseline version - use for an existing database
# When running migrations for the first time on an existing DB, set:
# migration.baseline=1.0
