include "common"


user {
  MasterAdmin = 1                 # Zdenek Kaplan
  MapDesigners = [32, 126]        # Jan Wild, Josef Bruna
  TaxonManager = 11               # Jiri Danihelka
  TaxonRanksManager = 11          # Jiri Danihelka
  HerbariumsManager = 1
  FindersManager = 1
  TraitMasterAdmin = 146          # Marcela Reznickova
  TraitUserAdmin = 104            # Milan Chytry
  MapUserAdmin = 1                # Zdenek Kaplan
  BulkImporter = 120          # hromadne importy
  Florabase = 32                   # Jan Wild
  
  AsyncImporters = ["vojta@kalcik.cz", "martin.rohn@gmail.com", "novotp@natur.cuni.cz"]
}

license.default = "P-P-P"  #default record license name
license.creative-commons-ids = ["CC-BY-SA", "CC-BY"]

taxonDistributionTraitId = 2973

excludedTaxonIdsFromTraits = [6697]

taxonGroup = vascular #vascular|nonvascular

allTaxaForRevisor = false

hasAtlasModule = true
hasTraitModule = true
hasBiblioModule = true
