include "common"

user {
  MasterAdmin = 20000               # Senko
  MapDesigners = [20000]            # Senko
  TaxonManager = [20000]            # Senko
  TaxonRanksManager = 20000         # Senko
  HerbariumsManager = 20000         # Senko
  FindersManager = 20000            # Senko
  TraitMasterAdmin = 20000          # Senko
  TraitUserAdmin = 20000            # Senko
  MapUserAdmin = 20000              # Senko
  BulkImporter = 20000              # Senko
  Florabase = 20000                 # Senko
}

license.default = "CC-BY-SA"  #default record license name
license.creative-commons-ids = ["CC-BY-SA", "CC-BY"]

taxonGroup = vascular #vascular|nonvascular

dbGeomUtmSrid = 32634
map.geoserverCommonUrl = "https://geoserver.sav.sk"
map.center = "[19.65, 48.6]"
map.zoom = 7.7
map.extent = "[1860548, 6050614, 2516547, 6389514]"

check.minAltitude = 80
check.maxAltitude = 2660
